name: build-web

on:
  push:
    branches:
      - main

env:
  REPO_NAME: ${{ github.repository }}
  PROJECT_NAME: ${{ github.event.repository.name }}
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: web
          file: ./web/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:web-latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
